### ISSUE TITLE
Farmer:wait_until_visible takes from 3 to 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by pilonull** [farshadz1997/Microsoft-Rewards-bot-GUI#2]
Hello, 

Just recently noticed that this GUI version exists, thanks for your continued development and work that you've put in to this project.

I'm running it on an Ubuntu 22.04.1 LTS VM and it seems to be hanging on the "Logging in" section.

It DOES launch a chromium window and logs in to the MS Account page, but after that the chromium window seems to crash or something?

This is what the errors.txt has in it:

```
-------------------2022-12-11 12:40:42.468609-------------------
Farmer.wait_until_visible() takes from 3 to 4 positional arguments but 5 were given

-------------------2022-12-11 12:43:00.542464-------------------
Farmer.wait_until_visible() takes from 3 to 4 positional arguments but 5 were given
```

and this is what the terminal window running main.pyw has in it: 

```
Traceback (most recent call last):
  File "/home/alex/Desktop/Microsoft-Rewards-bot-GUI-master/src/farmer.py", line 1220, in run
    self.login(account["username"], account["password"])
  File "/home/alex/Desktop/Microsoft-Rewards-bot-GUI-master/src/farmer.py", line 358, in login
    self.wait_until_visible(self.browser, By.ID, 'KmsiCheckboxField', 10)
TypeError: Farmer.wait_until_visible() takes from 3 to 4 positional arguments but 5 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alex/Desktop/Microsoft-Rewards-bot-GUI-master/src/farmer.py", line 1202, in perform_run
    return self.run()
  File "/home/alex/Desktop/Microsoft-Rewards-bot-GUI-master/src/farmer.py", line 1355, in run
    self.check_internet_connection()
  File "/home/alex/Desktop/Microsoft-Rewards-bot-GUI-master/src/farmer.py", line 99, in check_internet_connection
    si = subprocess.STARTUPINFO()
AttributeError: module 'subprocess' has no attribute 'STARTUPINFO'

```

Thanks again,

-Alex

**Comment by farshadz1997** [comment]
Hello,

thanks for letting me know, I'm going to upload the fix as soon as I can.

**Comment by farshadz1997** [comment]
tell me if you still have problem.

**Comment by pilonull** [comment]
> tell me if you still have problem.

Seems to be working great now, thank you!
